version: "3.9"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/gamebox-backend:latest  # Cambiado de build: .
    container_name: gamebox-back
    restart: always
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/gamebox?authSource=admin
      - NODE_ENV=production
      - PORT=3000
      # Agrega aqu√≠ otras variables de tu .env si las necesitas
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend-net

  mongo:
    image: mongo:6
    container_name: gamebox-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  mongo_data:
